# Generated by Django 4.2.11 on 2025-06-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0015_delete_appointment_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realization',
            options={'ordering': ['-date'], 'verbose_name': 'realizacja', 'verbose_name_plural': 'realizacje'},
        ),
    ]
